version: "3.8"

services:
  service-1:
    build: ./service-1
    image: jackparryqa/service-1:latest
    container_name: service-1
    ports:
    - target: 5000
      published: 5000
    depends_on:
      - service-2
      - service-3
      - service-4
    environment:
      DATABASE_URI: ${DATABASE_URI}
    deploy:
      replicas: 3
  service-2:
    build: ./service-2
    image: jackparryqa/service-2:latest
    container_name: service-2
    deploy:
      replicas: 3
  service-3:
    build: ./service-3
    image: jackparryqa/service-3:latest
    container_name: service-3
    deploy:
      replicas: 3
  service-4:
    build: ./service-4
    image: jackparryqa/service-4:latest
    container_name: service-4
    deploy:
      replicas: 3
                    
