version: "3.8"

services:
    nginx:
        image: nginx:latest
        ports: 
            - target: 80
    service-1:
        image: jackparryqa/service-1:1
        build: ./service-1
        ports:
            - target: 5000
              published: 5000
        # networks:
        #     - my_network
        # depends_on:
        #   - service-2
        #   - service-3
        #   - service-4
    service-2:
        image: jackparryqa/service-2
        build: ./service-2
        ports:
            - target: 5000
              published: 5001
        # networks:
        #     - my_network
    service-3:
        image: jackparryqa/service-3
        build: ./service-3
        ports:
            - target: 5000
              published: 5002
        # networks:
        #     - my_network
    service-4:
        image: jackparryqa/service-4
        build: ./service-4
        ports:
            - target: 5000
              published: 5003
        # networks:
        #     - my_network
                    

# networks:
#     my_network:
#         driver: overlay