---
# tasks file for nginx
- name: Install NGINX
  apt:
    name: nginx
    state: latest
    update_cache: true
- name: Start NGINX Service
  service:
    name: nginx
    state: started
- name: Add NGINX conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
- name: Restart NGINX
  service:
    name: nginx
    state: restarted
