all:
  children:
    managers:
      hosts:
        manager-1:
    workers:
      hosts:
        worker-1:
    load-balancer:
      hosts:
        10.164.0.2
      
  vars:
    ansible_user: jenkins
    ansible_ssh_private_key_file: '~/.ssh/ansible_id_rsa'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
