- hosts: managers
  become: true
  roles:
  - docker
  - manager
- hosts: workers
  become: true
  roles:
  - docker
  - worker
- hosts: 34.90.99.236           #nginx vm instance
  become: true
  roles:
    nginx
