- hosts: managers
  become: true
  roles:
  - docker
  - manager
- hosts: workers
  become: true
  roles:
  - docker
  - worker
- hosts: 34.91.116.27             #nginx vm instance
  become: true
  roles:
  - nginx
